---
- name: Créer le dossier d'instalaltion ~/powerdns
  ansible.builtin.file:
    path: ~/powerdns
    state: directory

- name: Copier le fichier docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: ~/powerdns/docker-compose.yml

- name: Lancer les conteneurs pour powerdns
  community.docker.docker_compose:
    project_src: ~/powerdns
    state: present
