---
- name : Install powerdns
  hosts: powerdns
  become: true

  pre_tasks:
    - name: include vars file
      include_vars: "vars.yml"

  tasks:
    - include_tasks: playbook/vm/requirements.yml
    - include_tasks: playbook/vm/install_mariadb.yml
    - include_tasks: playbook/vm/disable_resolv.yml
    - include_tasks: playbook/vm/install_pdns.yml
    - include_tasks: playbook/vm/install_nodejs_and_yarn.yml
    - include_tasks: playbook/vm/install_pdns_frontend.yml
    - include_tasks: playbook/vm/install_nginx.yml
    - include_tasks: playbook/vm/create_pdns_systemfils.yml
    - include_tasks: playbook/vm/security_allow_port.yml