---
- name: Download shell script for Node.js repository
  get_url:
    url: https://deb.nodesource.com/setup_16.x
    dest: /tmp/setup_node.sh

- name: Execute Node.js shell script
  shell: bash /tmp/setup_node.sh

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Download and Import Yarn GPG key and Add Yarn APT repository
  shell: |
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key --keyring /usr/share/keyrings/yarn-repository.gpg add -
    echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Yarn package
  apt:
    name: yarn
    state: present
