---
- name: Remove /var/www/html/pdns if it exists
  file:
    path: /var/www/html/pdns
    state: absent

- name: Clone PowerDNS Admin source code
  git:
    repo: https://github.com/ngoduykhanh/PowerDNS-Admin.git
    dest: /var/www/html/pdns

- name: Create and Activate virtual environment
  shell: |
    virtualenv -p python3 flask
    source ./flask/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    deactivate
  args:
    chdir: /var/www/html/pdns
    executable: /bin/bash

- name: Update default_config.py file
  template:
    src: templates/vm/default_config.py.j2
    dest: /var/www/html/pdns/powerdnsadmin/default_config.py

- name: Copy requirement file
  template:
    src: templates/vm/requirements.txt.j2
    dest: /var/www/html/pdns/requirements.txt

- name: Create and Activate virtual environment for upgrade flask
  shell: |
    source ./flask/bin/activate
    export FLASK_APP=powerdnsadmin/__init__.py
    flask db upgrade
    yarn install --pure-lockfile
    flask assets build
    deactivate
  args:
    chdir: /var/www/html/pdns
    executable: /bin/bash

- name: Update pdns.conf file to /etc/powerdns
  template:
    src: templates/vm/pdns.conf.j2
    dest: /etc/powerdns/pdns.conf

- name: Restart PowerDNS service
  systemd:
    name: pdns
    state: restarted