---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Ensure UFW is enabled
  ufw:
    state: enabled

- name: Allow PDNS port
  ufw:
    rule: allow
    port: "{{ server_port }}"

- name: Allow port 53
  ufw:
    rule: allow
    port: "53"