---
- name: Install UFW Firewall
  apt:
    name: ufw
    state: present

- name: Ensure UFW is enabled
  ufw:
    state: enabled

- name: Allow {{ server_port }} for PDNS access
  ufw:
    rule: allow
    port: "{{ server_port }}"

- name: Allow port 53 for DNS server
  ufw:
    rule: allow
    port: "53"

- name: Allow SSH connexion
  ufw:
    rule: allow
    port: "22"