---
- name: Check the symbolic link for /etc/resolv.conf
  command: ls -lh /etc/resolv.conf

- name: Remove the symbolic link for /etc/resolv.conf
  command: sudo unlink /etc/resolv.conf

- name: Update the resolv.conf file
  template:
    src: templates/vm/resolv.conf.j2
    dest: /etc/resolv.conf