---
- name: Add pdns source_list file
  template:
    src: templates/vm/pdns.list.j2
    dest: /etc/apt/sources.list.d

- name: Import the GPG key signing for the repository
  shell: curl -fsSL https://repo.powerdns.com/FD380FBB-pub.asc | sudo gpg -o /etc/apt/trusted.gpg.d/pdns.gpg

- name: Set the APT preferences
  template:
    src: templates/vm/pdns.j2
    dest: /etc/apt/preferences.d

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PowerDNS from the default APT
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - pdns-server
    - pdns-backend-mysql

- name: Import powedns dtatbase schema
  mysql_db:
    name: "{{ database_name }}"
    state: import
    target: /usr/share/pdns-backend-mysql/schema/schema.mysql.sql
    login_user: "{{ database_user }}"
    login_password: "{{ database_admin_password }}"
  ignore_errors: true

- name: Set pdns.local.gmysql.conf file
  template:
    src: templates/vm/pdns.local.gmysql.conf.j2
    dest: /etc/powerdns/pdns.d/pdns.local.gmysql.conf

- name: Change ownership of pdns.local.gmysql.conf
  file:
    path: /etc/powerdns/pdns.d/pdns.local.gmysql.conf
    owner: pdns
    group: pdns

- name: Change permissions of pdns.local.gmysql.conf
  file:
    path: /etc/powerdns/pdns.d/pdns.local.gmysql.conf
    mode: "0640"

- name: Stop pdns.service
  systemd:
    name: pdns
    state: stopped

- name: Start pdns_server with specific options
  command: pdns_server --daemon=no --guardian=no --loglevel=9
  async: 10
  poll: 0
  register: process_result
  ignore_errors: true
  
- name: Restart pdns service
  systemd:
    name: pdns
    state: restarted

- name: Enable pdns service
  systemd:
    name: pdns
    enabled: yes

- name: Check pdns service status
  command: ss -alnp4 | grep pdns