---
- name: Download MariaDB installation script
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup
    mode: '0755'

- name: Execute mariadb script
  command: bash mariadb_repo_setup
  args:
    chdir: /tmp

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MariaDB
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - mariadb-client

- name: Démarrer et activer MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Copy my.cnf to ~/.my.cnf on ansible host
  template: 
    src: .my.cnf.j2
    dest: ~/.my.cnf
  delegate_to: localhost

- name: Create a database named {{ database_name }}
  mysql_db:
    name: "{{ database_name }}"
    state: present
    login_user: root
    login_password_file: ~/.my.cnf

- name: Grant all privileges to {{ database_user }} on {{ database_name }}
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_admin_password }}"
    priv: "{{ database_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ database_admin_password }}"

- name: Update the privileges
  mysql_user:
    name: "{{ database_user }}"
    priv: "{{ database_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ database_admin_password }}"
    append_privs: yes

- name: Refresh the privileges
  command: mysql -e "FLUSH PRIVILEGES;"