---
- name: Download MariaDB installation script
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup
    mode: '0755'

- name: Execute mariadb script
  command: bash mariadb_repo_setup
  args:
    chdir: /tmp

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MariaDB
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - mariadb-client

- name: Run and activate MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: VCheck if root password is defined
  shell: mysql -u root -p{{ database_admin_password }} -e "SELECT 1 FROM mysql.user WHERE User='root' AND authentication_string != '' LIMIT 1"
  register: root_password_check
  changed_when: false
  ignore_errors: true

- name: Set root password
  mysql_user:
    name: root
    password: "{{ database_admin_password }}"
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ database_admin_password }}"
    check_implicit_admin: yes

- name: Copy my.cnf to ~/.my.cnf on ansible host
  template:
    src: templates/vm/my.cnf.j2
    dest: /root/.my.cnf
    mode: '0600'
  delegate_to: localhost

- name: Create database named {{ database_name }}
  mysql_db:
    name: "{{ database_name }}"
    state: present
    login_user: root
    login_password: "{{ database_admin_password }}"

- name: Grant all privileges
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_admin_password }}"
    priv: "{{ database_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ database_admin_password }}"

- name: Update the privileges
  mysql_user:
    name: "{{ database_user }}"
    priv: "{{ database_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ database_admin_password }}"
    append_privs: yes