---
- name: Add Node.js repository
  shell: curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn repository GPG key
  shell:
    cmd: echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present
    update_cache: yes
